project:
  type: website
  render:
    - "*.qmd"
    - "research/**"
    - "people/**"
    - "software/**"
    - "protocols/**"
    - "datasets/**"
    - "teaching/**"
    - "news/**"
    - "join/**"
    - "contact/**"
    - "!legacy_site/**"

website:
  title: "Briseño Lab"

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true

