project:
  type: website
  render:
    - "*.qmd"
    - "research/**"
    - "people/**"
    - "software/**"
    - "protocols/**"
    - "datasets/**"
    - "teaching/**"
    - "news/**"
    - "publications/**"
    - "join/**"
    - "contact/**"
    - "!legacy_site/**"

website:
  title: "Briseño Lab"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: research/
        text: Research

      - href: people/
        text: People

      - href: publications/
        text: Publications

      - href: software/
        text: Software

      - href: teaching/
        text: Teaching

      - href: news/
        text: News

      - href: join/
        text: Join Us

      - href: contact/
        text: Contact

bibliography: references/publications.bib

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: true
    anchor-sections: false

website:
  title: "Briseño Lab"

  google-analytics:
    tracking-id: "G-AB12CDE345"
    anonymize-ip: true

  cookie-consent: true
