## Principal Investigator

[Dr. Ricardo I. Alcalá Briseño](ricardo.qmd) \
Assistant Professor of Viral Ecology, Department of Plant Pathology and Environmental Microbiology, One Health Microbiome Center, Plant Sciences Institute, Virology Group, at  Penn State University

## Current Members

### Graduate Students

- [**Patricia Soria Venegas**](graduate/patricia_soria.qmd)  — Ph.D. Student \
- **Meghan Shoger** — M.S. Student (co-advised with Dr. David M. Beyer)

### Undergraduate Students

- **Reece P. Porter** — Undergraduate Volunteer

### Staff

- **Serenity Mathews** — Laboratory Manager, Mushroom Research Center (MRC)

### Postdoctoral Researchers

*Positions available.* 
https://psu.wd1.myworkdayjobs.com/PSU_Academic/job/Penn-State-University-Park/Postdoctoral-Scholar_REQ_0000078733-1?


## Collaborators

- **Dr. David M. Beyer** — Department of Plant Pathology and Environmental Microbiology; Director, Mushroom Research Center, Penn State
- **Dr. Tomás A. Rush** — Biosciences Division, Oak Ridge National Laboratory
- **Dr. Patrick F. Suthers** — Department of Chemical Engineering, Penn State
